"""Shadow candidate registry — Phase 7 of the historical-data program.

The strongest validated model is registered here as a *versioned shadow
candidate*. It is deliberately NOT wired into ``config/active.yaml`` or
``config/production/production_v1.yaml`` — promotion requires (a) real-world
head-to-head evidence from a shadow run against the production primary, and
(b) an explicit decision. The registry is the single record of what the
candidate is, why it was selected, and what promotion requires.

Candidates use the versioned experimental configs generated by
``research.calibration`` (expected_points_v1_hist / expected_minutes_v1_hist)
which never appear in the active version map, so production behaviour is
unchanged until a promotion decision is made.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import pandas as pd

from research import config as rconfig

logger = logging.getLogger(__name__)

# Walk-forward results used to justify the candidate (fold1: train 22-23 ->
# validate 23-24; fold2: train 22-23+23-24 -> validate 24-25). Metric labels
# match the ablation table columns in research/validation.py.
CANDIDATES = {
    "v3_hist_d_team": {
        "model_id": "v3_hist_d_team",
        "display_name": "V3-HIST-01 (Model D)",
        "ablation_model": "D_team",
        "points_version": "expected_points_v1_hist",
        "minutes_version": "expected_minutes_v1_hist",
        "hist_features": ["player", "team"],
        "fit_seasons": ["2022-23", "2023-24", "2024-25"],
        "status": "shadow_candidate",
        "promotion_status": "not_promoted",
        "rationale": (
            "Best overall walk-forward candidate. Versus the production "
            "baseline (Model A) across 2023-24 + 2024-25 it improves RMSE "
            "(-0.15/-0.15), bias (-0.41/-0.37), correlation (+0.06/+0.07) and "
            "predicted-vs-actual top-10 gameweek overlap (+0.42/+0.44), at a "
            "small MAE cost (+0.06/+0.02) driven by the minutes model's "
            "came-off-the-bench branch. Start probability accuracy improves "
            "(+0.08). Team-strength features add value over the points-only "
            "model (B); previous-season priors (F) add little and hurt fold2 "
            "start accuracy, so D (not F) is the candidate."
        ),
        "promotion_requires": [
            "Register as a shadow model for at least 5 consecutive gameweeks",
            "Head-to-head MAE/RMSE vs production primary over the shadow window",
            "Manual decision (never auto-promote)",
        ],
    },
    "v3_hist_b_points": {
        "model_id": "v3_hist_b_points",
        "display_name": "V3-HIST-B (Model B)",
        "ablation_model": "B_points_hist",
        "points_version": "expected_points_v1_hist",
        "minutes_version": None,
        "hist_features": [],
        "fit_seasons": ["2022-23", "2023-24", "2024-25"],
        "status": "shadow_candidate",
        "promotion_status": "not_promoted",
        "rationale": (
            "Incremental, lowest-risk upgrade: empirical xPts/90 calibration "
            "only (finishing/creative/bonus/clean-sheet). Improves RMSE, bias "
            "and correlation with near-identical MAE; changes no minutes logic."
        ),
        "promotion_requires": [
            "Register as a shadow model for at least 5 consecutive gameweeks",
            "Head-to-head MAE/RMSE vs production primary over the shadow window",
            "Manual decision (never auto-promote)",
        ],
    },
}


def get_candidate(candidate_id: str) -> dict:
    """Return a candidate definition by model_id (raises KeyError if absent)."""
    try:
        return CANDIDATES[candidate_id]
    except KeyError:
        raise KeyError(
            f"unknown shadow candidate {candidate_id!r}; available: {sorted(CANDIDATES)}"
        ) from None


def get_shadow_candidate() -> dict:
    """Return the primary (strongest) shadow candidate."""
    return CANDIDATES["v3_hist_d_team"]


def register_shadow_candidate(candidate_id: str | None = None) -> Path:
    """Write the candidate record with live ablation metrics to the results dir.

    ``candidate_id`` defaults to the strongest candidate (v3_hist_d_team).
    """
    cid = candidate_id or "v3_hist_d_team"
    candidate = dict(get_candidate(cid))

    metrics = {}
    try:
        table = pd.read_csv(rconfig.RESULTS_DIR / "ablation_summary.csv")
        for _, row in table[table["model"] == candidate["ablation_model"]].iterrows():
            metrics[row["fold"]] = {
                "mae_points": row["mae_points"],
                "rmse_points": row["rmse_points"],
                "bias_points": row["bias_points"],
                "corr_points": row["corr_points"],
                "mae_minutes": row["mae_minutes"],
                "start_accuracy": row["start_accuracy"],
                "top10_overlap_mean": row["top10_overlap_mean"],
            }
    except (FileNotFoundError, KeyError):
        logger.warning("ablation metrics unavailable; registering candidate without metrics")

    candidate["walk_forward_metrics"] = metrics
    path = rconfig.RESULTS_DIR / "shadow_candidate.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(candidate, f, indent=2)
    logger.info("registered shadow candidate %s -> %s", cid, path)
    return path


def load_shadow_candidate() -> dict:
    """Read the registered shadow-candidate record."""
    path = rconfig.RESULTS_DIR / "shadow_candidate.json"
    if not path.exists():
        raise FileNotFoundError("no shadow candidate registered yet; run register_shadow_candidate()")
    with open(path) as f:
        return json.load(f)
