"""Walk-forward validation + model ablation — Phase 6 of the historical program.

Models A-F (per the directive's ablation):
    A  baseline                 production v1 configs, no historical features
    B  points-hist              empirical xPts/90 calibration (finishing/creative/
                                bonus/clean-sheet) on top of v1 minutes
    C  minutes-hist             probability-weighted minutes (start/sub/unused)
                                on top of v1 points
    D  team                     B + C + empirical team strength (hist_team_*)
    F  full                     D + previous-season player priors (hist_prev_*)
    E  preseason                2026-27 preseason prior — structurally validated
                                only (no 2026-27 gameweeks exist yet)

Evidence framework (Phase 3 of that program):
    G  evidence                 D's engines + the evidence layer (ev_*): per-group
                                current-vs-historical weights driven by accumulated
                                evidence volume (research/evidence.py), replacing
                                the fixed prev-season/team shrinkage in the engines.

Walk-forward folds (train → validate; train is always fully before validate):
    fold1: 2022-23      -> 2023-24
    fold2: 2022-23+23-4 -> 2024-25

Every model reads configs generated by ``research.calibration`` (versioned YAML,
never the production configs) and injects only leakage-safe ``hist_*`` / ``ev_*``
features.
"""

from __future__ import annotations

import logging

import numpy as np
import pandas as pd

from research import config as rconfig
from research.backtest import run_season_backtest

logger = logging.getLogger(__name__)

POINTS_BASE = "expected_points_v1_hist"
MINUTES_BASE = "expected_minutes_v1_hist"

FOLDS = [
    {"name": "fold1", "train": ["2022-23"], "validate": ["2023-24"]},
    {"name": "fold2", "train": ["2022-23", "2023-24"], "validate": ["2024-25"]},
]

MODELS = {
    "A_baseline": {
        "points_version": None,
        "minutes_version": None,
        "hist_features": (),
        "desc": "V3 v1 baseline (production configs)",
    },
    "B_points_hist": {
        "points_version": POINTS_BASE,
        "minutes_version": None,
        "hist_features": (),
        "desc": "+empirical xPts/90 calibration",
    },
    "C_minutes_hist": {
        "points_version": None,
        "minutes_version": MINUTES_BASE,
        "hist_features": ("player",),
        "desc": "+probability-weighted minutes (start/sub/unused)",
    },
    "D_team": {
        "points_version": POINTS_BASE,
        "minutes_version": MINUTES_BASE,
        "hist_features": ("player", "team"),
        "desc": "+team strength (B+C)",
    },
    "F_full": {
        "points_version": POINTS_BASE,
        "minutes_version": MINUTES_BASE,
        "hist_features": ("player", "team", "prev"),
        "desc": "+prev-season priors (D)",
    },
    "G_evidence": {
        "points_version": POINTS_BASE,
        "minutes_version": MINUTES_BASE,
        "hist_features": ("player",),
        "evidence_version": "evidence_v1",
        "desc": "+evidence layer (current-season evidence weights, ev_*)",
    },
}


def _fold_versions(fold: dict) -> tuple[str, str]:
    suffix = fold["name"]  # "fold1" / "fold2"
    return f"{POINTS_BASE}_{suffix}", f"{MINUTES_BASE}_{suffix}"


def run_fold(
    fold: dict,
    models: list[str] | None = None,
    use_cache: bool = True,
    progress: bool = True,
) -> dict[str, pd.DataFrame]:
    """Run every selected model over the fold's validation seasons.

    Returns {model_id: DataFrame} with one row per (season, round, player).
    Results are cached per (fold, model, season) under data_research/results/.
    """
    pv, mv = _fold_versions(fold)
    models = models or list(MODELS)
    out: dict[str, pd.DataFrame] = {}

    for model in models:
        spec = MODELS[model]
        points_version = spec["points_version"]
        minutes_version = spec["minutes_version"]
        evidence_version = spec.get("evidence_version")
        if points_version == POINTS_BASE:
            points_version = pv
        if minutes_version == MINUTES_BASE:
            minutes_version = mv

        frames = []
        for season in fold["validate"]:
            tag = f"{model}_{fold['name']}"
            cache = rconfig.RESULTS_DIR / f"v3_{tag}_predictions.csv"
            if use_cache and cache.exists():
                df = pd.read_csv(cache)
                logger.info("[%s] loaded cached %s", model, cache.name)
            else:
                df = run_season_backtest(
                    season,
                    points_version=points_version,
                    minutes_version=minutes_version,
                    hist_features=spec["hist_features"],
                    evidence_version=evidence_version,
                    tag=tag,
                    progress=progress,
                )
                cache.parent.mkdir(parents=True, exist_ok=True)
                df.to_csv(cache, index=False)
                logger.info("[%s] wrote %d rows to %s", model, len(df), cache)
            frames.append(df)
        out[model] = pd.concat(frames, ignore_index=True)
    return out


def run_ablation(
    use_cache: bool = True, progress: bool = True
) -> dict[str, dict[str, pd.DataFrame]]:
    """Run all folds for all models. Returns {fold_name: {model: DataFrame}}."""
    results = {}
    for fold in FOLDS:
        logger.info(
            "running fold %s (train=%s validate=%s)",
            fold["name"],
            fold["train"],
            fold["validate"],
        )
        results[fold["name"]] = run_fold(fold, use_cache=use_cache, progress=progress)
    return results


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------


def evaluate_outcome(
    out: pd.DataFrame,
    pred_col: str = "predicted_points",
    actual_col: str = "actual_points",
) -> pd.DataFrame:
    """Row-level (season, round, player) outcome frame with error columns."""
    df = out.dropna(subset=[pred_col, actual_col]).copy()
    df["points_error"] = df[pred_col] - df[actual_col]
    df["points_abs_error"] = df["points_error"].abs()
    df["minutes_error"] = df["expected_minutes"] - df["actual_minutes"]
    df["minutes_abs_error"] = df["minutes_error"].abs()
    df["predicted_start"] = (df["start_probability"] >= 0.5).astype(int)
    df["actual_start"] = df["actual_starts"].astype(int)
    df["is_non_starter"] = df["actual_start"] == 0
    df["actual_sub_appearance"] = (
        (df["actual_starts"] == 0) & (df["actual_minutes"] > 0)
    ).astype(int)
    df["sub_rate_error"] = df["sub_rate_given_not_start"] - df["actual_sub_appearance"]
    return df


def summarize_model(
    out: pd.DataFrame,
    pred_col: str = "predicted_points",
    actual_col: str = "actual_points",
) -> dict:
    """Aggregate metrics for one model's pooled fold output."""
    df = evaluate_outcome(out, pred_col, actual_col)
    s = {}
    s["n_predictions"] = len(df)
    if df.empty:
        return s
    s["mae_points"] = float(df["points_abs_error"].mean())
    s["rmse_points"] = float(np.sqrt((df["points_error"] ** 2).mean()))
    s["bias_points"] = float(df["points_error"].mean())
    s["corr_points"] = float(df[pred_col].corr(df[actual_col]))
    s["mae_minutes"] = float(df["minutes_abs_error"].mean())
    s["minutes_mae_faithful"] = float(df["minutes_abs_error"].mean())
    s["start_accuracy"] = float((df["predicted_start"] == df["actual_start"]).mean())
    ns = df[df["is_non_starter"]]
    if not ns.empty:
        s["sub_rate_mae"] = float(ns["sub_rate_error"].abs().mean())
        s["sub_rate_bias"] = float(ns["sub_rate_error"].mean())
        s["n_non_starters"] = len(ns)
    # Top-10 hit rate: predicted top-10 vs actual top-10 by points per gameweek.
    overlaps = []
    for (season, gw), g in df.groupby(["season", "round"]):
        pred_top = set(g.sort_values(pred_col, ascending=False).head(10)["player_id"])
        act_top = set(g.sort_values(actual_col, ascending=False).head(10)["player_id"])
        overlaps.append(len(pred_top & act_top))
    s["top10_overlap_mean"] = float(np.mean(overlaps)) if overlaps else float("nan")
    return s


def build_ablation_table(results: dict[str, dict[str, pd.DataFrame]]) -> pd.DataFrame:
    """Comparison table: fold x model x metrics."""
    rows = []
    for fold_name, models in results.items():
        for model_id, df in models.items():
            row = {
                "fold": fold_name,
                "model": model_id,
                "desc": MODELS[model_id]["desc"],
            }
            row.update(summarize_model(df))
            rows.append(row)
    return pd.DataFrame(rows)


def save_ablation(results: dict[str, dict[str, pd.DataFrame]]) -> pd.DataFrame:
    table = build_ablation_table(results)
    rconfig.RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    table.to_csv(rconfig.RESULTS_DIR / "ablation_summary.csv", index=False)
    return table


# ---------------------------------------------------------------------------
# Preseason (Model E) — structural validation only
# ---------------------------------------------------------------------------


def run_preseason_validation() -> dict:
    """Structural validation of the 2026-27 preseason prior (Model E)."""
    from research.preseason import (
        build_preseason_prior,
        run_preseason_baseline,
        validate_preseason_prior,
    )

    prior = build_preseason_prior()
    checks = validate_preseason_prior(prior)
    baseline = run_preseason_baseline()
    report = {
        "checks": checks,
        "n_players": len(prior),
        "gw1_baseline_rows": len(baseline),
        "top_gw1_xpts": baseline.sort_values("predicted_points", ascending=False)[
            ["web_name", "position", "predicted_points"]
        ]
        .head(10)
        .to_dict("records"),
    }
    report_path = rconfig.RESULTS_DIR / "preseason_gw1_baseline.csv"
    baseline.to_csv(report_path, index=False)
    return report
