"""baseline schema

Revision ID: 129653672751
Revises: 
Create Date: 2026-08-02 19:25:56.014137

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '129653672751'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chip_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('chip_name', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('used_in_gameweek', sa.Integer(), nullable=True),
    sa.Column('recommended_in_gameweek', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chip_state_team_id'), 'chip_state', ['team_id'], unique=False)
    op.create_table('decision_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(), nullable=False),
    sa.Column('recommendation_json', sa.String(), nullable=False),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('action_json', sa.String(), nullable=True),
    sa.Column('predicted_points', sa.Float(), nullable=True),
    sa.Column('actual_points', sa.Float(), nullable=True),
    sa.Column('was_accurate', sa.Boolean(), nullable=True),
    sa.Column('confidence_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_log_gameweek_id'), 'decision_log', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_decision_log_team_id'), 'decision_log', ['team_id'], unique=False)
    op.create_table('experiment_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_name', sa.String(), nullable=False),
    sa.Column('experiment_type', sa.String(), nullable=False),
    sa.Column('baseline_version', sa.String(), nullable=True),
    sa.Column('treatment_version', sa.String(), nullable=True),
    sa.Column('config_diff', sa.JSON(), nullable=True),
    sa.Column('baseline_mae', sa.Float(), nullable=True),
    sa.Column('treatment_mae', sa.Float(), nullable=True),
    sa.Column('improvement_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('deadline_time', sa.String(), nullable=True),
    sa.Column('deadline_time_epoch', sa.Integer(), nullable=True),
    sa.Column('deadline_time_game_offset', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('data_checked', sa.Boolean(), nullable=True),
    sa.Column('is_previous', sa.Boolean(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_next', sa.Boolean(), nullable=True),
    sa.Column('most_captained', sa.Integer(), nullable=True),
    sa.Column('most_vice_captained', sa.Integer(), nullable=True),
    sa.Column('transferred_in', sa.Integer(), nullable=True),
    sa.Column('highest_score', sa.Integer(), nullable=True),
    sa.Column('chip_plays', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_tag', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('weights_snapshot', sa.JSON(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('coverage_80', sa.Float(), nullable=True),
    sa.Column('coverage_95', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_tag')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('strength_overall_home', sa.Integer(), nullable=True),
    sa.Column('strength_overall_away', sa.Integer(), nullable=True),
    sa.Column('strength_attack_home', sa.Integer(), nullable=True),
    sa.Column('strength_attack_away', sa.Integer(), nullable=True),
    sa.Column('strength_defence_home', sa.Integer(), nullable=True),
    sa.Column('strength_defence_away', sa.Integer(), nullable=True),
    sa.Column('pulse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine_accuracy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('engine_name', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('contribution_score', sa.Float(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['prediction_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_accuracy_gameweek_id'), 'engine_accuracy', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_engine_accuracy_version_id'), 'engine_accuracy', ['version_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('web_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('element_type', sa.Integer(), nullable=False),
    sa.Column('now_cost', sa.Integer(), nullable=True),
    sa.Column('cost_change_start', sa.Integer(), nullable=True),
    sa.Column('cost_change_event', sa.Integer(), nullable=True),
    sa.Column('cost_change_start_fall', sa.Integer(), nullable=True),
    sa.Column('cost_change_event_fall', sa.Integer(), nullable=True),
    sa.Column('value_form', sa.Float(), nullable=True),
    sa.Column('value_season', sa.Float(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals_scored', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('clean_sheets', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('own_goals', sa.Integer(), nullable=True),
    sa.Column('penalties_saved', sa.Integer(), nullable=True),
    sa.Column('penalties_missed', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('bps', sa.Integer(), nullable=True),
    sa.Column('influence', sa.Float(), nullable=True),
    sa.Column('creativity', sa.Float(), nullable=True),
    sa.Column('threat', sa.Float(), nullable=True),
    sa.Column('ict_index', sa.Float(), nullable=True),
    sa.Column('expected_goals', sa.Float(), nullable=True),
    sa.Column('expected_assists', sa.Float(), nullable=True),
    sa.Column('expected_goal_involvements', sa.Float(), nullable=True),
    sa.Column('expected_goals_conceded', sa.Float(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('event_points', sa.Integer(), nullable=True),
    sa.Column('form', sa.Float(), nullable=True),
    sa.Column('selected_by_percent', sa.Float(), nullable=True),
    sa.Column('transfers_in_event', sa.Integer(), nullable=True),
    sa.Column('transfers_out_event', sa.Integer(), nullable=True),
    sa.Column('transfers_in', sa.Integer(), nullable=True),
    sa.Column('transfers_out', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('news', sa.String(), nullable=True),
    sa.Column('chance_of_playing_next_round', sa.Integer(), nullable=True),
    sa.Column('chance_of_playing_this_round', sa.Integer(), nullable=True),
    sa.Column('news_added', sa.String(), nullable=True),
    sa.Column('penalties_order', sa.Integer(), nullable=True),
    sa.Column('direct_freekicks_order', sa.Integer(), nullable=True),
    sa.Column('corners_and_indirect_freekicks_order', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('element_type_str', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_gameweek_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team', sa.Integer(), nullable=True),
    sa.Column('was_home', sa.Boolean(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals_scored', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('clean_sheets', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('own_goals', sa.Integer(), nullable=True),
    sa.Column('penalties_saved', sa.Integer(), nullable=True),
    sa.Column('penalties_missed', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('bps', sa.Integer(), nullable=True),
    sa.Column('influence', sa.Float(), nullable=True),
    sa.Column('creativity', sa.Float(), nullable=True),
    sa.Column('threat', sa.Float(), nullable=True),
    sa.Column('ict_index', sa.Float(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('expected_goals', sa.Float(), nullable=True),
    sa.Column('expected_assists', sa.Float(), nullable=True),
    sa.Column('expected_goal_involvements', sa.Float(), nullable=True),
    sa.Column('expected_goals_conceded', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('selected', sa.Float(), nullable=True),
    sa.Column('transfers_in', sa.Integer(), nullable=True),
    sa.Column('transfers_out', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=False),
    sa.Column('now_cost', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals_scored', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('clean_sheets', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('expected_goals', sa.Float(), nullable=True),
    sa.Column('expected_assists', sa.Float(), nullable=True),
    sa.Column('expected_goal_involvements', sa.Float(), nullable=True),
    sa.Column('expected_goals_conceded', sa.Float(), nullable=True),
    sa.Column('form', sa.Float(), nullable=True),
    sa.Column('selected_by_percent', sa.Float(), nullable=True),
    sa.Column('influence', sa.Float(), nullable=True),
    sa.Column('creativity', sa.Float(), nullable=True),
    sa.Column('threat', sa.Float(), nullable=True),
    sa.Column('ict_index', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('news', sa.String(), nullable=True),
    sa.Column('chance_of_playing_next_round', sa.Integer(), nullable=True),
    sa.Column('chance_of_playing_this_round', sa.Integer(), nullable=True),
    sa.Column('transfers_in_event', sa.Integer(), nullable=True),
    sa.Column('transfers_out_event', sa.Integer(), nullable=True),
    sa.Column('xgi_per_90', sa.Float(), nullable=True),
    sa.Column('minutes_fraction', sa.Float(), nullable=True),
    sa.Column('team_strength_raw', sa.Float(), nullable=True),
    sa.Column('fixture_score_raw', sa.Float(), nullable=True),
    sa.Column('set_piece_raw', sa.Float(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_snapshots_gameweek_id'), 'player_snapshots', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_player_snapshots_player_id'), 'player_snapshots', ['player_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=False),
    sa.Column('ci_80_low', sa.Float(), nullable=True),
    sa.Column('ci_80_high', sa.Float(), nullable=True),
    sa.Column('ci_95_low', sa.Float(), nullable=True),
    sa.Column('ci_95_high', sa.Float(), nullable=True),
    sa.Column('minutes_proj', sa.Float(), nullable=True),
    sa.Column('goals_proj', sa.Float(), nullable=True),
    sa.Column('assists_proj', sa.Float(), nullable=True),
    sa.Column('clean_sheet_proj', sa.Float(), nullable=True),
    sa.Column('bonus_proj', sa.Float(), nullable=True),
    sa.Column('other_proj', sa.Float(), nullable=True),
    sa.Column('actual_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['prediction_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projections_gameweek_id'), 'projections', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_projections_player_id'), 'projections', ['player_id'], unique=False)
    op.create_index(op.f('ix_projections_version_id'), 'projections', ['version_id'], unique=False)
    op.create_table('recommendation_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_log_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('player_out_id', sa.Integer(), nullable=True),
    sa.Column('player_in_id', sa.Integer(), nullable=True),
    sa.Column('player_out_actual_pts', sa.Float(), nullable=True),
    sa.Column('player_in_actual_pts', sa.Float(), nullable=True),
    sa.Column('was_acted_on', sa.Boolean(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_log_id'], ['decision_log.id'], ),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['player_in_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_out_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['prediction_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_outcomes_decision_log_id'), 'recommendation_outcomes', ['decision_log_id'], unique=False)
    op.create_index(op.f('ix_recommendation_outcomes_gameweek_id'), 'recommendation_outcomes', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_recommendation_outcomes_version_id'), 'recommendation_outcomes', ['version_id'], unique=False)
    op.create_table('validation_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('bias', sa.Float(), nullable=True),
    sa.Column('median_ae', sa.Float(), nullable=True),
    sa.Column('coverage_80', sa.Float(), nullable=True),
    sa.Column('coverage_95', sa.Float(), nullable=True),
    sa.Column('ci_width_avg', sa.Float(), nullable=True),
    sa.Column('mae_by_position', sa.JSON(), nullable=True),
    sa.Column('rmse_by_position', sa.JSON(), nullable=True),
    sa.Column('n_by_position', sa.JSON(), nullable=True),
    sa.Column('best_predicted_player_id', sa.Integer(), nullable=True),
    sa.Column('worst_predicted_player_id', sa.Integer(), nullable=True),
    sa.Column('worst_error', sa.Float(), nullable=True),
    sa.Column('n_projections', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['best_predicted_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['prediction_versions.id'], ),
    sa.ForeignKeyConstraint(['worst_predicted_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_metrics_gameweek_id'), 'validation_metrics', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_validation_metrics_version_id'), 'validation_metrics', ['version_id'], unique=False)
    op.create_table('error_classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('projection_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('error', sa.Float(), nullable=False),
    sa.Column('abs_error', sa.Float(), nullable=False),
    sa.Column('error_direction', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('error_severity', sa.String(), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('predicted_minutes', sa.Float(), nullable=True),
    sa.Column('actual_minutes', sa.Float(), nullable=True),
    sa.Column('predicted_goals', sa.Float(), nullable=True),
    sa.Column('actual_goals', sa.Integer(), nullable=True),
    sa.Column('predicted_assists', sa.Float(), nullable=True),
    sa.Column('actual_assists', sa.Integer(), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['projection_id'], ['projections.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['prediction_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_classifications_gameweek_id'), 'error_classifications', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_error_classifications_player_id'), 'error_classifications', ['player_id'], unique=False)
    op.create_index(op.f('ix_error_classifications_projection_id'), 'error_classifications', ['projection_id'], unique=False)
    op.create_index(op.f('ix_error_classifications_version_id'), 'error_classifications', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_classifications_version_id'), table_name='error_classifications')
    op.drop_index(op.f('ix_error_classifications_projection_id'), table_name='error_classifications')
    op.drop_index(op.f('ix_error_classifications_player_id'), table_name='error_classifications')
    op.drop_index(op.f('ix_error_classifications_gameweek_id'), table_name='error_classifications')
    op.drop_table('error_classifications')
    op.drop_index(op.f('ix_validation_metrics_version_id'), table_name='validation_metrics')
    op.drop_index(op.f('ix_validation_metrics_gameweek_id'), table_name='validation_metrics')
    op.drop_table('validation_metrics')
    op.drop_index(op.f('ix_recommendation_outcomes_version_id'), table_name='recommendation_outcomes')
    op.drop_index(op.f('ix_recommendation_outcomes_gameweek_id'), table_name='recommendation_outcomes')
    op.drop_index(op.f('ix_recommendation_outcomes_decision_log_id'), table_name='recommendation_outcomes')
    op.drop_table('recommendation_outcomes')
    op.drop_index(op.f('ix_projections_version_id'), table_name='projections')
    op.drop_index(op.f('ix_projections_player_id'), table_name='projections')
    op.drop_index(op.f('ix_projections_gameweek_id'), table_name='projections')
    op.drop_table('projections')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_player_snapshots_player_id'), table_name='player_snapshots')
    op.drop_index(op.f('ix_player_snapshots_gameweek_id'), table_name='player_snapshots')
    op.drop_table('player_snapshots')
    op.drop_table('player_gameweek_stats')
    op.drop_table('snapshots')
    op.drop_table('players')
    op.drop_index(op.f('ix_engine_accuracy_version_id'), table_name='engine_accuracy')
    op.drop_index(op.f('ix_engine_accuracy_gameweek_id'), table_name='engine_accuracy')
    op.drop_table('engine_accuracy')
    op.drop_table('teams')
    op.drop_table('prediction_versions')
    op.drop_table('gameweeks')
    op.drop_table('experiment_runs')
    op.drop_index(op.f('ix_decision_log_team_id'), table_name='decision_log')
    op.drop_index(op.f('ix_decision_log_gameweek_id'), table_name='decision_log')
    op.drop_table('decision_log')
    op.drop_index(op.f('ix_chip_state_team_id'), table_name='chip_state')
    op.drop_table('chip_state')
    # ### end Alembic commands ###
